# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Rich Wallace
title: Software Developer III
email: riwalaz@gmail.com
website: www.github.com/richwallace

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: riwalaz
github_username:  richwallace
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: riwalaz
linkedin_username: richwallace
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Rich and I'm a senior integration software developer. During my career in the world of Information Technology, I have been involved in most all areas of the technoloy stack including first level support, multi-network administration, database development and admin, and a wide range of software development using a plethora of different languages and protocols. Experience with a number of enterprise level companies have also offered me valuable teamwork and leadership skills.

  I am most skilled in: <mark>Azure Cloud Development</mark>, <mark>Microsoft/Azure SQL</mark>, and <mark>OData w/ASP.NET Web APIs</mark>.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Enterprise Data Hub
        quote: >
          Centralized enterise data repository housing all shared data/business objects that span across the business organization
          Utilizes a Microservices architecture with ASP.NET Web APIs, OData, Azure SQL, Azure Service Bus, and Kubernetes
        description: | # this will include new lines to allow paragraphs
          This was my introduction to the world of Web APIs and Azure/cloud based development and has grown from an idea, to a fully functional flagship product used by all other business verticals managing up to well over 2mil transactions per day.  I'm extremely proud of the outcome of the project and have learned much more about not only the current technologies, but software development as a whole.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: PulteGroup Inc.
        link: www.pultegroupinc.com
        # link_text: boringcompany.com
        sub_title: Software Developer III / Lead Dev
        caption: May 2015 - Present
        quote: >
          Data/Application Integration - Lead Dev focused on Azure based data integration solutions
        description: | # this will include new lines to allow paragraphs
            When you think of the "Homebuilding Industry", leading edge technology and robust data delivery, management, and consumption is not the first thing that comes to mind.  Digging holes and hammering nails is difficult work and I play my part making sure the whole company stays connected.  I lead a small but powerful team of 5 people and enjoy driving the company to try new technologies.

      - layout: left
        title: BlueCross BlueShield of Arizona
        caption: 2012 - 2015
        sub_title: Team Lead/Senior Software Developer
        quote: >
          Led the Data Integration team in developing and maintaining mission critical insurance related transaction processing in real-time
        description: | # this will include new lines to allow paragraphs
          The health insurance world is interesting, to say the least.  As part of the backend data integration team. I implemented integrations responsible for transforming EDI documents to HL7 documents for cross platform processing,
          architected integration between BCBS daily processes and Healthcare.gov when launched nationally, oversaw implementation of RESTful APIs to sunset legacy WCF and homegrown web services, and directed my team in delivering business critical BizTalk workflows with Foresight for EDH processing in real-time for claims and eligibility transactions.
          
      - layout: left
        title: JFShea Co., Inc.
        caption: 1999 - 2012
        sub_title: Senior Software Developer
        quote: >
          Introduced SOA (Service Oriented Achitecure) and real-time data integration and reporting with WCF and BizTalk Server
        description: | # this will include new lines to allow paragraphs
          After battling the scary Y2K threat, I was able to find my way into the world of professional software development while transitioning from the role of a MS SQL Server database administrator.  While here, I was exposed to Microsoft's BizTalk Server before full release and with this new tool, I reduced maintenance on job processing by transforming them to automated SSIS and BizTalk tasks and 
          led other development teams from point-to-point homegrown integration to a real-time publish/subscribe based architecture.

      - layout: left
        title: Choice Hotels International
        caption: 1996 - 1999
        sub_title: Lead Systems Analyst
        quote: >
          Joined the exciting realm of technical support, network administration, database development, and software delivery 
        description: | # this will include new lines to allow paragraphs
          As I entered the career life, I found myself working in a high-paced hospitality industry that was in the middle of transforming their entire technology stack from MS-DOS and floppy disks to desktops, servers, and satellite connectivity.  Here, I led third level support and analysis team for property systems implemented with over 3,000 properties, filled the role as liaison between support and development teams to discuss and implement enhancements and new features, spearheaded SQL script development to provide global support tools for support teams so that they no longer needed to rely on DBAs and on-call schedules, and implemented formalized training and documentation for all IT personnel for newly installed properties with Windows based property management suite.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: InterfaceTT
        link: interfacett.com
        link_text: interfacett.com
        sub_title: Project Management (PMP)
        caption: May 2011
        quote: >
          Project Management Professional Certification Prep
        description: | # this will include new lines to allow paragraphs
            Although I had no intentions of becoming a project manager, I had interest in growing my career as a leader in the software development world, and based on how the software development lifecycle continues on, it made sense to learn and understand how to manage projects and use those skills in my path to greatness.

      - layout: left
        title: InterfaceTT
        link: interfacett.com
        link_text: interfacett.com
        sub_title: Project Management (PMP)
        caption: May 2011
        quote: >
          AZ-204T00-A - Developing Solutions for Microsoft Azure
        description: | # this will include new lines to allow paragraphs
            Create end-to-end solutions in Microsoft Azure.  Learned how to implement Azure compute solutions, create Azure Functions, implement and manage web apps, develop solutions utilizing Azure storage, implement authentication and authorization, and secure solutions by using KeyVault and Managed Identities.

  - title: Professional Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      As part of building my professional career and feeding my interests in software development, here are some of my other skiils:
      - Azure / Cloud Development and Administration
      - ASP.NET Web API w/OData and Azure SQL
      - NoSQL databases, such as CosmosDd and MongoDb
      - Microsoft SQL Server InNtegration Services and Azure Data Factory
      - Azure Service Bus and Azure Event Grid
      - Azure Logic Apps and Functions

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in technology and software engineering, some of my other interests and hobbies are:
      - Weight lifting
      - PC gaming and streaming
      - Hanging out with my kids, grandkids, and my Chihuahua

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
